fix: rename the prompt commands and allow shellPreExec to stop a command to run

diff --git a/productivity b/productivity
--- a/productivity
+++ b/productivity
@@ -96,53 +96,40 @@ function prdvty::envPathAdd {
 #fi
 
 typeset -i PRDVTY_LOADTIME="$(date +%s)"
-typeset -a PRDVTY_PROMPTFUNCCB=() PRDVTY_PREEXECCB=() PRDVTY_POSTEXECCB=()
-typeset -i PRDVTY_PREEXECTIME=0
-typeset    PRDVTY_PREEXECCMD=
-function prdvty::promptfunc {
-	typeset retcode=${1:-$?}
+typeset -a PRDVTY_PREEXECCB=() PRDVTY_POSTEXECCB=()
 
-	# Call our post-exec hooks
-	prdvty::shellPostExec "$retcode"
 
-	typeset cb
-	for cb in ${PRDVTY_PROMPTFUNCCB[@]}; do
-		[ -n "$cb" ] || continue
-		$cb $retcode
-	done
-
-}
-
-function prdvty::promptfuncRegister {
-	PRDVTY_PROMPTFUNCCB+=("$*")
-}
-
-function prdvty::postexecfuncRegister {
+function prdvty::shellPostExecRegister {
 	PRDVTY_POSTEXECCB+=("$*")
 }
 
+function prdvty::shellPreExecRegister {
+	PRDVTY_PREEXECCB+=("$*")
+}
 
 # preexec is called by bash "trap DEBUG". called before executing a cmd
 function prdvty::shellPreExec {
-	# Skip our own PROMPT_COMMAND to reset our stats
-	[ "${BASH_COMMAND%% *}" == "prdvty::promptfunc" ] && return
+	# Skip our own PROMPT_COMMAND and disable extdebug after a non-zero callback
+	if [ "${BASH_COMMAND%% *}" == "prdvty::shellPostExec" ]; then
+		shopt -u extdebug
+		return
+	fi
 
 	# Call out pre-exec callbacks
 	typeset cb
 	for cb in ${PRDVTY_PREEXECCB[@]}; do
 		[ -n "$cb" ] || continue
-		$cb
+		# extdebug is needed to prevent the execution of a command.
+		# It'll be disabled after a successful callback, or after calling the shellPostExec command
+		shopt -s extdebug
+		$cb || return 1
+		shopt -u extdebug
 	done
-	PRDVTY_PREEXECTIME="${SECONDS:-$(date +%s)}"
-	PRDVTY_PREEXECCMD+="${PRDVTY_PREEXECCMD:+ | }$BASH_COMMAND"
-	#echo "Preeec: $PRDVTY_PREEXECCMD at $prdvty::PREEXECTIME"
 }
 
 # PostExec is called by promptfunc, itself called by the shell PROMPT_COMMAND
 function prdvty::shellPostExec {
-	typeset retcode="$1"
-
-	#echo "Postexec: took $((${SECONDS:-$(date +%s)} - $PRDVTY_PREEXECTIME ))s for $prdvty::PREEXECCMD"
+	typeset retcode=${1:-$?}
 
 	# Call our post-exec callbacks
 	typeset cb
@@ -150,9 +137,6 @@ function prdvty::shellPostExec {
 		[ -n "$cb" ] || continue
 		$cb "$retcode"
 	done
-
-	# Reset the callback for pre-exec
-	PRDVTY_PREEXECCMD=""
 }
 
 # -----------------------------------------------------------------------------
@@ -178,7 +162,7 @@ for moddir in "$__PRDVTY_ROOT/modules/"*; do
 done
 
 # At the end, replace the PROMPT_COMMAND by ours
-PROMPT_COMMAND='prdvty::promptfunc $?'
+PROMPT_COMMAND='prdvty::shellPostExec $?'
 trap 'prdvty::shellPreExec' DEBUG
 
 # vim: ft=sh
